name: he_dash
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip=22.0.3
  - python=3.10.4
  - pytest=7.3
  - black=22.6.0
  - dash=2.9.3
  - plotly=5.14.1
  - numpy=1.24.2
  - pandas=2.0.0
  - scipy=1.7
  - scikit-learn=1.2.2
  - ipykernel=6.15.1
  - black-jupyter=22.6.0
  - pip:
    - dash[testing]